services:
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    #pull_policy: always
    command: ["server", "local"]
    user: "root"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:8080"
      - "81:8081"
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          server:
            basicAuth:
              enabled: true
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          storage:
            type: local
            local:
              basePath: "/app/storage"
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/