apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\wydar\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kestra
  name: kestra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kestra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\wydar\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: kestra
    spec:
      containers:
        - args:
            - server
            - local
          env:
            - name: KESTRA_CONFIGURATION
              value: |-
                kestra:
                  server:
                    basicAuth:
                      enabled: true
                      username: "admin@kestra.io" # it must be a valid email address
                      password: kestra
                  storage:
                    type: local
                    local:
                      basePath: "/app/storage"
                  tasks:
                    tmpDir:
                      path: /tmp/kestra-wd/tmp
                  url: http://localhost:8080/
          image: kestra/kestra:latest
          name: kestra
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
